version: '3.9'
services:
  client:
    build:
      context: ./client
    ports:
      - '5173:5173'
    depends_on:
      - server
  server:
    container_name: realtime-client
    build:
      context: ./server
    ports:
      - '3001:3001'
