runtime: nodejs
env: flex
instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1 # Can adjust this as needed
  cool_down_period_sec: 120 # Time in seconds that the service will wait after a new instance is started before starting another instance
  cpu_utilization:
    target_utilization: 0.65 # Adjust based on desired CPU utilization before scaling
